#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : seahorse
Version  : 42.0
Release  : 25
URL      : https://download.gnome.org/sources/seahorse/42/seahorse-42.0.tar.xz
Source0  : https://download.gnome.org/sources/seahorse/42/seahorse-42.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.1 GPL-2.0 LGPL-2.1
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gcr-data
BuildRequires : gnupg
BuildRequires : gsettings-desktop-schemas
BuildRequires : openldap-dev
BuildRequires : openssh
BuildRequires : p11-kit-dev
BuildRequires : pkgconfig(gcr-3)
BuildRequires : pkgconfig(gcr-4)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : vala

%description
Seahorse
========
Seahorse is a graphical interface for managing and using encryption keys.
Currently it supports PGP keys (using GPG/GPGME) and SSH keys. Its goal is to
provide an easy to use key management tool, along with an easy to use interface
for encryption operations.

%prep
%setup -q -n seahorse-42.0
cd %{_builddir}/seahorse-42.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663966331
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dkey-sharing=false \
-Dmanpage=true  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
target=$HOME/.local/share/glib-2.0/schemas
mkdir -p $target
glib-compile-schemas --targetdir=$target /usr/share/glib-2.0/schemas
export XDG_DATA_DIRS="$HOME/.local/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/seahorse
cp %{_builddir}/seahorse-%{version}/COPYING %{buildroot}/usr/share/package-licenses/seahorse/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/seahorse-%{version}/COPYING-DOCS %{buildroot}/usr/share/package-licenses/seahorse/c61905dc64311e8bcee6afc425fa40f917a45131 || :
cp %{_builddir}/seahorse-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/seahorse/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
